// Questions from Directory 2 - Unique ones not in Directory 1
import { Difficulty, AMCATQuestion } from "./amcat-questions";

export const directory2Questions: AMCATQuestion[] = [
    {
        title: "Count Pairs and Remaining Integers",
        slug: "count-pairs-remaining-integers",
        difficulty: Difficulty.EASY,
        statement: `A company transmits a message consisting of integers. The transmission system can only send pairs of identical integers (exactly two at a time). The process continues until no more such pairs can be formed.\n\nYour task is to determine:\n1. The total number of pairs transmitted\n2. The number of integers remaining unpaired`,
        inputFormat: `First line contains an integer N representing the number of integers.\nSecond line contains N space-separated integers.`,
        outputFormat: `Print two space-separated integers: pairs_transmitted and remaining_integers.`,
        constraints: `1 <= N <= 10^5\n1 <= arr[i] <= 10^6`,
        sampleInput: `7\n1 2 1 2 1 3 2`,
        sampleOutput: `2 3`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "implementation"],
        testCases: [
            { input: "7\n1 2 1 2 1 3 2", output: "2 3", isSample: true },
            { input: "4\n1 1 1 1", output: "2 0", isSample: false },
            { input: "1\n5", output: "0 1", isSample: false },
            { input: "2\n1 1", output: "1 0", isSample: false },
            { input: "6\n1 1 2 2 3 3", output: "3 0", isSample: false },
            { input: "5\n1 2 3 4 5", output: "0 5", isSample: false },
            { input: "8\n1 1 1 1 2 2 2 2", output: "4 0", isSample: false },
            { input: "3\n5 5 5", output: "1 1", isSample: false },
            { input: "6\n10 10 20 20 30 30", output: "3 0", isSample: false },
            { input: "4\n1 2 3 1", output: "1 2", isSample: false },
        ],
    },
    {
        title: "Frequency of Characters in String",
        slug: "frequency-characters-string",
        difficulty: Difficulty.EASY,
        statement: `You are given a lowercase string. Your task is to count the frequency of each character present in the string.\n\nThe output should display only the characters that appear in the string, sorted in alphabetical order, along with their frequency.`,
        inputFormat: `A string S.`,
        outputFormat: `Each character followed by ':' and its count.`,
        constraints: `1 <= len(S) <= 10^4`,
        sampleInput: `programming`,
        sampleOutput: `a:1\ng:2\ni:1\nm:2\nn:1\no:1\np:1\nr:2`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["strings", "implementation"],
        testCases: [
            { input: "programming", output: "a:1\ng:2\ni:1\nm:2\nn:1\no:1\np:1\nr:2", isSample: true },
            { input: "a", output: "a:1", isSample: false },
            { input: "aaa", output: "a:3", isSample: false },
            { input: "abc", output: "a:1\nb:1\nc:1", isSample: false },
            { input: "hello", output: "e:1\nh:1\nl:2\no:1", isSample: false },
            { input: "zzz", output: "z:3", isSample: false },
            { input: "test", output: "e:1\ns:1\nt:2", isSample: false },
            { input: "abcabc", output: "a:2\nb:2\nc:2", isSample: false },
        ],
    },
    {
        title: "Find Second Largest Element",
        slug: "find-second-largest-element",
        difficulty: Difficulty.EASY,
        statement: `Given an array of integers, find the second largest distinct element.\n\nIf the second largest element does not exist (array size < 2 or all values are same), print -1.`,
        inputFormat: `First line contains integer N.\nSecond line contains N space-separated integers.`,
        outputFormat: `Second largest element or -1.`,
        constraints: `1 <= N <= 10^5\n-10^9 <= arr[i] <= 10^9`,
        sampleInput: `5\n10 20 4 45 99`,
        sampleOutput: `45`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays"],
        testCases: [
            { input: "5\n10 20 4 45 99", output: "45", isSample: true },
            { input: "3\n5 5 5", output: "-1", isSample: false },
            { input: "2\n1 2", output: "1", isSample: false },
            { input: "1\n5", output: "-1", isSample: false },
            { input: "5\n1 2 3 4 5", output: "4", isSample: false },
            { input: "4\n100 100 50 50", output: "50", isSample: false },
            { input: "6\n10 10 20 20 30 30", output: "20", isSample: false },
            { input: "3\n-5 -10 -3", output: "-5", isSample: false },
            { input: "4\n1 1 1 2", output: "1", isSample: false },
            { input: "5\n99 98 97 96 95", output: "98", isSample: false },
        ],
    },
    {
        title: "Remove Duplicate Elements",
        slug: "remove-duplicate-elements",
        difficulty: Difficulty.EASY,
        statement: `Given an array of integers, remove duplicate elements while preserving the original order.\n\nOnly the first occurrence of each element should remain.`,
        inputFormat: `Array size and elements.`,
        outputFormat: `Array after removing duplicates.`,
        constraints: `1 <= N <= 10^5`,
        sampleInput: `7\n1 2 3 1 2 4 5`,
        sampleOutput: `1 2 3 4 5`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "implementation"],
        testCases: [
            { input: "7\n1 2 3 1 2 4 5", output: "1 2 3 4 5", isSample: true },
            { input: "1\n5", output: "5", isSample: false },
            { input: "4\n1 1 1 1", output: "1", isSample: false },
            { input: "5\n1 2 3 4 5", output: "1 2 3 4 5", isSample: false },
            { input: "6\n1 2 1 2 1 2", output: "1 2", isSample: false },
            { input: "5\n5 4 3 2 1", output: "5 4 3 2 1", isSample: false },
            { input: "8\n1 1 2 2 3 3 4 4", output: "1 2 3 4", isSample: false },
            { input: "3\n10 10 10", output: "10", isSample: false },
            { input: "6\n1 2 3 3 2 1", output: "1 2 3", isSample: false },
        ],
    },
    {
        title: "Count Even and Odd Numbers",
        slug: "count-even-odd-numbers",
        difficulty: Difficulty.EASY,
        statement: `Given an array of integers, count how many numbers are even and how many are odd.`,
        inputFormat: `Array size and elements.`,
        outputFormat: `Two integers: even_count and odd_count.`,
        constraints: `1 <= N <= 10^5`,
        sampleInput: `6\n1 2 3 4 5 6`,
        sampleOutput: `3 3`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "math"],
        testCases: [
            { input: "6\n1 2 3 4 5 6", output: "3 3", isSample: true },
            { input: "1\n2", output: "1 0", isSample: false },
            { input: "1\n1", output: "0 1", isSample: false },
            { input: "4\n2 4 6 8", output: "4 0", isSample: false },
            { input: "5\n1 3 5 7 9", output: "0 5", isSample: false },
            { input: "3\n0 1 2", output: "2 1", isSample: false },
            { input: "8\n1 2 3 4 5 6 7 8", output: "4 4", isSample: false },
            { input: "2\n100 101", output: "1 1", isSample: false },
            { input: "5\n10 20 30 40 50", output: "5 0", isSample: false },
        ],
    },
    {
        title: "Smallest Missing Positive Integer",
        slug: "smallest-missing-positive-integer",
        difficulty: Difficulty.MEDIUM,
        statement: `Given an array that may contain positive numbers, negative numbers, and zero, find the smallest positive integer that does not appear in the array.`,
        inputFormat: `Array size and elements.`,
        outputFormat: `Smallest missing positive integer.`,
        constraints: `1 <= N <= 10^5`,
        sampleInput: `6\n3 4 -1 1 0 2`,
        sampleOutput: `5`,
        timeLimit: 1000,
        memoryLimit: 256,
        hint: "Use the array indices to mark presence of numbers 1 to n.",
        tags: ["arrays"],
        testCases: [
            { input: "6\n3 4 -1 1 0 2", output: "5", isSample: true },
            { input: "3\n1 2 3", output: "4", isSample: false },
            { input: "1\n1", output: "2", isSample: false },
            { input: "1\n2", output: "1", isSample: false },
            { input: "5\n-1 -2 -3 -4 -5", output: "1", isSample: false },
            { input: "4\n1 2 3 5", output: "4", isSample: false },
            { input: "3\n2 3 4", output: "1", isSample: false },
            { input: "5\n1 1 1 1 1", output: "2", isSample: false },
            { input: "6\n7 8 9 10 11 12", output: "1", isSample: false },
            { input: "4\n1 2 0 4", output: "3", isSample: false },
        ],
    },
    {
        title: "Rotate Array Right by K",
        slug: "rotate-array-right-k",
        difficulty: Difficulty.EASY,
        statement: `Rotate the given array to the right by K positions. The rotation should be circular.`,
        inputFormat: `Array size, array elements, and integer K.`,
        outputFormat: `Rotated array.`,
        constraints: `1 <= N <= 10^5\n0 <= K <= 10^9`,
        sampleInput: `5\n1 2 3 4 5\n2`,
        sampleOutput: `4 5 1 2 3`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays"],
        testCases: [
            { input: "5\n1 2 3 4 5\n2", output: "4 5 1 2 3", isSample: true },
            { input: "3\n1 2 3\n0", output: "1 2 3", isSample: false },
            { input: "3\n1 2 3\n1", output: "3 1 2", isSample: false },
            { input: "4\n1 2 3 4\n4", output: "1 2 3 4", isSample: false },
            { input: "5\n1 2 3 4 5\n5", output: "1 2 3 4 5", isSample: false },
            { input: "6\n1 2 3 4 5 6\n3", output: "4 5 6 1 2 3", isSample: false },
            { input: "4\n10 20 30 40\n1", output: "40 10 20 30", isSample: false },
            { input: "3\n5 10 15\n10", output: "10 15 5", isSample: false },
        ],
    },
    {
        title: "Check Palindrome String",
        slug: "check-palindrome-string",
        difficulty: Difficulty.EASY,
        statement: `A string is called a palindrome if it reads the same forward and backward.\n\nCheck whether the given string is a palindrome.`,
        inputFormat: `A string.`,
        outputFormat: `PALINDROME or NOT PALINDROME.`,
        constraints: `1 <= len(S) <= 10^4`,
        sampleInput: `madam`,
        sampleOutput: `PALINDROME`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["strings"],
        testCases: [
            { input: "madam", output: "PALINDROME", isSample: true },
            { input: "hello", output: "NOT PALINDROME", isSample: false },
            { input: "a", output: "PALINDROME", isSample: false },
            { input: "aa", output: "PALINDROME", isSample: false },
            { input: "ab", output: "NOT PALINDROME", isSample: false },
            { input: "racecar", output: "PALINDROME", isSample: false },
            { input: "level", output: "PALINDROME", isSample: false },
            { input: "noon", output: "PALINDROME", isSample: false },
            { input: "world", output: "NOT PALINDROME", isSample: false },
            { input: "abba", output: "PALINDROME", isSample: false },
        ],
    },
    {
        title: "Sum of Digits Until Single Digit",
        slug: "sum-digits-until-single",
        difficulty: Difficulty.EASY,
        statement: `Given an integer, repeatedly sum its digits until the result becomes a single digit.`,
        inputFormat: `An integer.`,
        outputFormat: `Final single-digit result.`,
        constraints: `0 <= N <= 10^18`,
        sampleInput: `9875`,
        sampleOutput: `2`,
        timeLimit: 1000,
        memoryLimit: 256,
        hint: "This is the digital root: result is n % 9 (with special case for 0 and multiples of 9).",
        tags: ["math"],
        testCases: [
            { input: "9875", output: "2", isSample: true },
            { input: "99", output: "9", isSample: false },
            { input: "0", output: "0", isSample: false },
            { input: "1", output: "1", isSample: false },
            { input: "10", output: "1", isSample: false },
            { input: "18", output: "9", isSample: false },
            { input: "123", output: "6", isSample: false },
            { input: "999", output: "9", isSample: false },
            { input: "12345", output: "6", isSample: false },
            { input: "9999", output: "9", isSample: false },
        ],
    },
    {
        title: "Count Prime Numbers in Array",
        slug: "count-prime-numbers-array",
        difficulty: Difficulty.EASY,
        statement: `Given an array of integers, count how many of them are prime numbers.`,
        inputFormat: `Array size and elements.`,
        outputFormat: `Count of prime numbers.`,
        constraints: `1 <= N <= 10^4\n1 <= arr[i] <= 10^6`,
        sampleInput: `6\n1 2 3 4 5 6`,
        sampleOutput: `3`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "math"],
        testCases: [
            { input: "6\n1 2 3 4 5 6", output: "3", isSample: true },
            { input: "1\n2", output: "1", isSample: false },
            { input: "3\n4 6 8", output: "0", isSample: false },
            { input: "5\n2 3 5 7 11", output: "5", isSample: false },
            { input: "4\n1 1 1 1", output: "0", isSample: false },
            { input: "3\n10 20 30", output: "0", isSample: false },
            { input: "5\n13 17 19 23 29", output: "5", isSample: false },
            { input: "6\n1 4 6 8 9 10", output: "0", isSample: false },
        ],
    },
    {
        title: "Replace Element with Sum of Digits",
        slug: "replace-element-sum-digits",
        difficulty: Difficulty.EASY,
        statement: `Given an array of integers, replace each element with the sum of its digits.`,
        inputFormat: `Array size and elements.`,
        outputFormat: `Modified array.`,
        constraints: `1 <= N <= 10^4`,
        sampleInput: `4\n123 45 67 89`,
        sampleOutput: `6 9 13 17`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "math"],
        testCases: [
            { input: "4\n123 45 67 89", output: "6 9 13 17", isSample: true },
            { input: "1\n5", output: "5", isSample: false },
            { input: "2\n10 20", output: "1 2", isSample: false },
            { input: "3\n100 200 300", output: "1 2 3", isSample: false },
            { input: "4\n11 22 33 44", output: "2 4 6 8", isSample: false },
            { input: "3\n999 888 777", output: "27 24 21", isSample: false },
            { input: "5\n1 2 3 4 5", output: "1 2 3 4 5", isSample: false },
            { input: "2\n0 10", output: "0 1", isSample: false },
        ],
    },
    {
        title: "Find Missing Number 1 to N",
        slug: "find-missing-number-1-to-n",
        difficulty: Difficulty.EASY,
        statement: `You are given N-1 numbers from the range 1 to N. One number is missing.\n\nFind the missing number.`,
        inputFormat: `Integer N and N-1 integers.`,
        outputFormat: `Missing number.`,
        constraints: `2 <= N <= 10^6`,
        sampleInput: `5\n1 2 4 5`,
        sampleOutput: `3`,
        timeLimit: 1000,
        memoryLimit: 256,
        hint: "Use sum formula: N*(N+1)/2 - sum of given numbers.",
        tags: ["arrays", "math"],
        testCases: [
            { input: "5\n1 2 4 5", output: "3", isSample: true },
            { input: "3\n1 3", output: "2", isSample: false },
            { input: "2\n2", output: "1", isSample: false },
            { input: "4\n1 2 3", output: "4", isSample: false },
            { input: "6\n1 2 3 4 6", output: "5", isSample: false },
            { input: "10\n1 2 3 4 5 6 7 8 9", output: "10", isSample: false },
            { input: "5\n2 3 4 5", output: "1", isSample: false },
            { input: "3\n1 2", output: "3", isSample: false },
        ],
    },
    {
        title: "Count Words in Sentence",
        slug: "count-words-in-sentence",
        difficulty: Difficulty.EASY,
        statement: `Given a sentence, count the total number of words present.\n\nWords are separated by spaces.`,
        inputFormat: `A string sentence.`,
        outputFormat: `Number of words.`,
        constraints: `1 <= len(S) <= 10^4`,
        sampleInput: `Hello World This is AMCAT`,
        sampleOutput: `5`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["strings"],
        testCases: [
            { input: "Hello World This is AMCAT", output: "5", isSample: true },
            { input: "Hello", output: "1", isSample: false },
            { input: "a b c", output: "3", isSample: false },
            { input: "one two three four five", output: "5", isSample: false },
            { input: "test", output: "1", isSample: false },
            { input: "programming is fun", output: "3", isSample: false },
            { input: "a", output: "1", isSample: false },
            { input: "word1 word2 word3 word4", output: "4", isSample: false },
        ],
    },
    {
        title: "Check Perfect Number",
        slug: "check-perfect-number",
        difficulty: Difficulty.EASY,
        statement: `A perfect number is a number whose sum of proper divisors equals the number itself.\n\nCheck whether the given number is perfect.`,
        inputFormat: `An integer.`,
        outputFormat: `PERFECT or NOT PERFECT.`,
        constraints: `1 <= N <= 10^8`,
        sampleInput: `28`,
        sampleOutput: `PERFECT`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math"],
        testCases: [
            { input: "28", output: "PERFECT", isSample: true },
            { input: "12", output: "NOT PERFECT", isSample: false },
            { input: "6", output: "PERFECT", isSample: false },
            { input: "1", output: "NOT PERFECT", isSample: false },
            { input: "496", output: "PERFECT", isSample: false },
            { input: "100", output: "NOT PERFECT", isSample: false },
            { input: "10", output: "NOT PERFECT", isSample: false },
            { input: "8128", output: "PERFECT", isSample: false },
            { input: "5", output: "NOT PERFECT", isSample: false },
            { input: "2", output: "NOT PERFECT", isSample: false },
        ],
    },
    {
        title: "Print Number Pattern",
        slug: "print-number-pattern",
        difficulty: Difficulty.EASY,
        statement: `Given an integer N, print a pattern where each row prints numbers from 1 to the row number.`,
        inputFormat: `Integer N.`,
        outputFormat: `Required number pattern.`,
        constraints: `1 <= N <= 20`,
        sampleInput: `4`,
        sampleOutput: `1\n1 2\n1 2 3\n1 2 3 4`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["implementation"],
        testCases: [
            { input: "4", output: "1\n1 2\n1 2 3\n1 2 3 4", isSample: true },
            { input: "1", output: "1", isSample: false },
            { input: "2", output: "1\n1 2", isSample: false },
            { input: "3", output: "1\n1 2\n1 2 3", isSample: false },
            { input: "5", output: "1\n1 2\n1 2 3\n1 2 3 4\n1 2 3 4 5", isSample: false },
        ],
    },
];
