// Part B Questions (Q11-Q35) - Automata/PYQ Pool
import { Difficulty, DifficultyType, AMCATQuestion } from "./amcat-questions";

export const partB1Questions: AMCATQuestion[] = [
    {
        title: "Cell Competition",
        slug: "cell-competition",
        difficulty: Difficulty.MEDIUM,
        statement: `Given an array of cells (0 or 1), compute the next state after d days. On each day, each cell becomes 1 if its left and right neighbors differ, else it becomes 0. Cells at edges treat missing neighbors as 0.`,
        inputFormat: `Integer n\nn integers (0 or 1)\nInteger d (days)`,
        outputFormat: `Final array state after d days.`,
        constraints: `1 <= n <= 10\n0 <= d <= 1000`,
        sampleInput: `8\n1 0 0 0 0 1 0 0\n1`,
        sampleOutput: `0 1 0 0 1 0 1 0`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "implementation"],
        testCases: [
            { input: "8\n1 0 0 0 0 1 0 0\n1", output: "0 1 0 0 1 0 1 0", isSample: true },
            { input: "8\n0 0 0 0 0 0 0 0\n5", output: "0 0 0 0 0 0 0 0", isSample: false },
            { input: "8\n1 1 1 1 1 1 1 1\n1", output: "0 0 0 0 0 0 0 0", isSample: false },
            { input: "4\n1 0 1 0\n2", output: "0 0 0 0", isSample: false },
            { input: "6\n1 0 0 0 0 1\n1", output: "0 1 0 0 1 0", isSample: false },
            { input: "3\n1 1 1\n1", output: "0 0 0", isSample: false },
            { input: "5\n0 1 0 1 0\n1", output: "1 0 0 0 1", isSample: false },
            { input: "8\n1 0 0 0 0 1 0 0\n2", output: "1 0 0 1 0 1 0 1", isSample: false },
            { input: "4\n1 0 0 1\n3", output: "0 0 0 0", isSample: false },
            { input: "6\n0 1 1 0 0 1\n1", output: "1 0 1 1 1 0", isSample: false },
            { input: "8\n0 0 1 0 0 1 0 0\n1", output: "0 1 0 1 1 0 1 0", isSample: false },
        ],
    },
    {
        title: "Balanced Parentheses",
        slug: "balanced-parentheses",
        difficulty: Difficulty.EASY,
        statement: `Given a string containing parentheses ()[]{}. Check if they are balanced (every opening bracket has a matching closing bracket in correct order). Print YES if balanced, else NO.`,
        inputFormat: `Single string (parentheses only).`,
        outputFormat: `YES or NO`,
        constraints: `String length up to 10^4`,
        sampleInput: `{[()]}`,
        sampleOutput: `YES`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["strings", "implementation"],
        testCases: [
            { input: "{[()]}", output: "YES", isSample: true },
            { input: "{[(])}", output: "NO", isSample: false },
            { input: "((()))", output: "YES", isSample: false },
            { input: "(", output: "NO", isSample: false },
            { input: ")", output: "NO", isSample: false },
            { input: "", output: "YES", isSample: false },
            { input: "[]{}()", output: "YES", isSample: false },
            { input: "[{()}]", output: "YES", isSample: false },
            { input: "(((()", output: "NO", isSample: false },
            { input: "{{}}", output: "YES", isSample: false },
            { input: "([)]", output: "NO", isSample: false },
            { input: "{{[[(())]]}}", output: "YES", isSample: false },
        ],
    },
    {
        title: "Merge Two Sorted Lists",
        slug: "merge-two-sorted-lists",
        difficulty: Difficulty.EASY,
        statement: `Given two sorted arrays A and B, merge them into a single sorted array.`,
        inputFormat: `Integers n and m\nn integers (array A)\nm integers (array B)`,
        outputFormat: `Merged sorted array.`,
        constraints: `1 <= n, m <= 10^5`,
        sampleInput: `3 3\n1 4 7\n2 3 6`,
        sampleOutput: `1 2 3 4 6 7`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "sorting"],
        testCases: [
            { input: "3 3\n1 4 7\n2 3 6", output: "1 2 3 4 6 7", isSample: true },
            { input: "1 1\n1\n2", output: "1 2", isSample: false },
            { input: "2 3\n1 5\n2 3 4", output: "1 2 3 4 5", isSample: false },
            { input: "3 1\n10 20 30\n5", output: "5 10 20 30", isSample: false },
            { input: "4 4\n1 2 3 4\n5 6 7 8", output: "1 2 3 4 5 6 7 8", isSample: false },
            { input: "2 2\n1 1\n1 1", output: "1 1 1 1", isSample: false },
            { input: "3 2\n1 3 5\n2 4", output: "1 2 3 4 5", isSample: false },
            { input: "1 5\n100\n1 2 3 4 5", output: "1 2 3 4 5 100", isSample: false },
            { input: "5 1\n1 2 3 4 5\n3", output: "1 2 3 3 4 5", isSample: false },
            { input: "2 2\n10 20\n5 15", output: "5 10 15 20", isSample: false },
            { input: "3 3\n1 1 1\n2 2 2", output: "1 1 1 2 2 2", isSample: false },
        ],
    },
    {
        title: "Target Search in 2D Matrix",
        slug: "target-search-2d-matrix",
        difficulty: Difficulty.MEDIUM,
        statement: `Given a matrix where each row is sorted and the first element of each row > last element of previous row, search for target x. Return 0-based coordinates (i, j) if found, else return -1 -1.`,
        inputFormat: `Integers r and c\nr*c matrix elements (row by row)\nInteger x (target)`,
        outputFormat: `i j (0-based) or -1 -1.`,
        constraints: `1 <= r, c <= 100`,
        sampleInput: `2 3\n1 3 5\n7 9 11\n9`,
        sampleOutput: `1 1`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "binary-search"],
        testCases: [
            { input: "2 3\n1 3 5\n7 9 11\n9", output: "1 1", isSample: true },
            { input: "2 3\n1 3 5\n7 9 11\n6", output: "-1 -1", isSample: false },
            { input: "1 1\n5\n5", output: "0 0", isSample: false },
            { input: "1 1\n5\n3", output: "-1 -1", isSample: false },
            { input: "3 3\n1 2 3\n4 5 6\n7 8 9\n1", output: "0 0", isSample: false },
            { input: "3 3\n1 2 3\n4 5 6\n7 8 9\n9", output: "2 2", isSample: false },
            { input: "2 4\n1 2 3 4\n5 6 7 8\n7", output: "1 2", isSample: false },
            { input: "4 2\n1 2\n3 4\n5 6\n7 8\n5", output: "2 0", isSample: false },
            { input: "2 2\n1 2\n3 4\n10", output: "-1 -1", isSample: false },
            { input: "3 2\n10 20\n30 40\n50 60\n30", output: "1 0", isSample: false },
            { input: "1 5\n1 2 3 4 5\n3", output: "0 2", isSample: false },
        ],
    },
    {
        title: "GCD of Two Numbers",
        slug: "gcd-of-two-numbers",
        difficulty: Difficulty.EASY,
        statement: `Compute the greatest common divisor (GCD) of two integers a and b.`,
        inputFormat: `Two integers a and b.`,
        outputFormat: `Single integer (GCD).`,
        constraints: `1 <= a, b <= 10^9`,
        sampleInput: `18 24`,
        sampleOutput: `6`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math"],
        testCases: [
            { input: "18 24", output: "6", isSample: true },
            { input: "17 13", output: "1", isSample: false },
            { input: "100 25", output: "25", isSample: false },
            { input: "1 1", output: "1", isSample: false },
            { input: "1 100", output: "1", isSample: false },
            { input: "12 12", output: "12", isSample: false },
            { input: "48 18", output: "6", isSample: false },
            { input: "56 98", output: "14", isSample: false },
            { input: "1000000 500000", output: "500000", isSample: false },
            { input: "7 11", output: "1", isSample: false },
            { input: "36 60", output: "12", isSample: false },
            { input: "81 27", output: "27", isSample: false },
        ],
    },
    {
        title: "Reverse Second Half of Linked List",
        slug: "reverse-second-half-linked-list",
        difficulty: Difficulty.MEDIUM,
        statement: `Given a singly linked list, reverse only the second half in-place. If length is odd, the middle node belongs to the second half. Return head.`,
        inputFormat: `Integer n\nn integers (node values)`,
        outputFormat: `Values of modified list in order.`,
        constraints: `1 <= n <= 10^3`,
        sampleInput: `5\n1 2 3 4 5`,
        sampleOutput: `1 2 5 4 3`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["implementation"],
        testCases: [
            { input: "5\n1 2 3 4 5", output: "1 2 5 4 3", isSample: true },
            { input: "4\n1 2 3 4", output: "1 2 4 3", isSample: false },
            { input: "1\n5", output: "5", isSample: false },
            { input: "2\n1 2", output: "1 2", isSample: false },
            { input: "3\n1 2 3", output: "1 3 2", isSample: false },
            { input: "6\n1 2 3 4 5 6", output: "1 2 3 6 5 4", isSample: false },
            { input: "7\n10 20 30 40 50 60 70", output: "10 20 30 70 60 50 40", isSample: false },
            { input: "8\n1 2 3 4 5 6 7 8", output: "1 2 3 4 8 7 6 5", isSample: false },
            { input: "4\n5 5 5 5", output: "5 5 5 5", isSample: false },
            { input: "6\n6 5 4 3 2 1", output: "6 5 4 1 2 3", isSample: false },
            { input: "3\n100 200 300", output: "100 300 200", isSample: false },
        ],
    },
    {
        title: "Find Target in 2D Matrix",
        slug: "find-target-2d-matrix",
        difficulty: Difficulty.MEDIUM,
        statement: `Given a matrix and value x, return 0-based coordinates (i, j) where mat[i][j] == x. If not found, return -1 -1.`,
        inputFormat: `Integers r and c\nr rows of c integers each\nInteger x`,
        outputFormat: `i j (0-based) or -1 -1.`,
        constraints: `1 <= r, c <= 100`,
        sampleInput: `2 3\n1 3 5\n7 9 11\n9`,
        sampleOutput: `1 1`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays"],
        testCases: [
            { input: "2 3\n1 3 5\n7 9 11\n9", output: "1 1", isSample: true },
            { input: "2 2\n1 2\n3 4\n5", output: "-1 -1", isSample: false },
            { input: "1 1\n42\n42", output: "0 0", isSample: false },
            { input: "3 3\n1 2 3\n4 5 6\n7 8 9\n5", output: "1 1", isSample: false },
            { input: "2 4\n10 20 30 40\n50 60 70 80\n70", output: "1 2", isSample: false },
            { input: "4 2\n1 2\n3 4\n5 6\n7 8\n1", output: "0 0", isSample: false },
            { input: "3 3\n1 1 1\n1 1 1\n1 1 1\n1", output: "0 0", isSample: false },
            { input: "2 3\n5 10 15\n20 25 30\n100", output: "-1 -1", isSample: false },
            { input: "1 5\n1 2 3 4 5\n4", output: "0 3", isSample: false },
            { input: "5 1\n10\n20\n30\n40\n50\n30", output: "2 0", isSample: false },
            { input: "2 2\n0 0\n0 0\n0", output: "0 0", isSample: false },
        ],
    },
    {
        title: "Reverse Linked List Full",
        slug: "reverse-linked-list-full",
        difficulty: Difficulty.EASY,
        statement: `Reverse a singly linked list in-place and output the reversed sequence.`,
        inputFormat: `Integer n\nn integers (node values)`,
        outputFormat: `Reversed sequence.`,
        constraints: `1 <= n <= 10^4`,
        sampleInput: `4\n10 20 30 40`,
        sampleOutput: `40 30 20 10`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["implementation"],
        testCases: [
            { input: "4\n10 20 30 40", output: "40 30 20 10", isSample: true },
            { input: "1\n5", output: "5", isSample: false },
            { input: "2\n1 2", output: "2 1", isSample: false },
            { input: "5\n1 2 3 4 5", output: "5 4 3 2 1", isSample: false },
            { input: "3\n100 200 300", output: "300 200 100", isSample: false },
            { input: "6\n6 5 4 3 2 1", output: "1 2 3 4 5 6", isSample: false },
            { input: "4\n1 1 1 1", output: "1 1 1 1", isSample: false },
            { input: "5\n5 4 3 2 1", output: "1 2 3 4 5", isSample: false },
            { input: "7\n10 20 30 40 50 60 70", output: "70 60 50 40 30 20 10", isSample: false },
            { input: "3\n0 0 0", output: "0 0 0", isSample: false },
            { input: "2\n99 1", output: "1 99", isSample: false },
        ],
    },
    {
        title: "Merge Sort Implementation",
        slug: "merge-sort-implementation",
        difficulty: Difficulty.MEDIUM,
        statement: `Sort an array using merge sort.`,
        inputFormat: `Integer n\nn integers (unsorted array)`,
        outputFormat: `Sorted array.`,
        constraints: `1 <= n <= 10^4`,
        sampleInput: `5\n3 1 4 1 5`,
        sampleOutput: `1 1 3 4 5`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["sorting"],
        testCases: [
            { input: "5\n3 1 4 1 5", output: "1 1 3 4 5", isSample: true },
            { input: "1\n5", output: "5", isSample: false },
            { input: "2\n2 1", output: "1 2", isSample: false },
            { input: "6\n6 5 4 3 2 1", output: "1 2 3 4 5 6", isSample: false },
            { input: "4\n1 1 1 1", output: "1 1 1 1", isSample: false },
            { input: "7\n7 3 5 1 9 2 8", output: "1 2 3 5 7 8 9", isSample: false },
            { input: "3\n100 50 75", output: "50 75 100", isSample: false },
            { input: "5\n1 2 3 4 5", output: "1 2 3 4 5", isSample: false },
            { input: "8\n8 7 6 5 4 3 2 1", output: "1 2 3 4 5 6 7 8", isSample: false },
            { input: "4\n10 30 20 40", output: "10 20 30 40", isSample: false },
            { input: "6\n5 5 5 5 5 5", output: "5 5 5 5 5 5", isSample: false },
        ],
    },
    {
        title: "Remove Vowels from String",
        slug: "remove-vowels-from-string",
        difficulty: Difficulty.EASY,
        statement: `Remove all vowels (a, e, i, o, u, case-insensitive) from a string.`,
        inputFormat: `Single string.`,
        outputFormat: `String with vowels removed.`,
        constraints: `String length up to 10^3`,
        sampleInput: `Automata`,
        sampleOutput: `tmT`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["strings", "implementation"],
        testCases: [
            { input: "Automata", output: "tmT", isSample: true },
            { input: "Hello", output: "Hll", isSample: false },
            { input: "aeiou", output: "", isSample: false },
            { input: "AEIOU", output: "", isSample: false },
            { input: "xyz", output: "xyz", isSample: false },
            { input: "Programming", output: "Prgrmmng", isSample: false },
            { input: "AaBbCc", output: "BbCc", isSample: false },
            { input: "test", output: "tst", isSample: false },
            { input: "Queue", output: "Q", isSample: false },
            { input: "bcdfg", output: "bcdfg", isSample: false },
            { input: "EeEeE", output: "", isSample: false },
        ],
    },
    {
        title: "Substring Replacement",
        slug: "substring-replacement",
        difficulty: Difficulty.EASY,
        statement: `Replace all non-overlapping occurrences of pattern 'pat' in string 's' with replacement string 'rep'.`,
        inputFormat: `Line 1: string s\nLine 2: pattern pat\nLine 3: replacement rep`,
        outputFormat: `Modified string.`,
        constraints: `Lengths up to 10^3`,
        sampleInput: `abcabcabc\nabc\nx`,
        sampleOutput: `xxx`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["strings"],
        testCases: [
            { input: "abcabcabc\nabc\nx", output: "xxx", isSample: true },
            { input: "hello\nl\nL", output: "heLLo", isSample: false },
            { input: "aaa\na\nb", output: "bbb", isSample: false },
            { input: "xyz\na\nb", output: "xyz", isSample: false },
            { input: "test\ntest\nREPLACED", output: "REPLACED", isSample: false },
            { input: "abab\nab\nxy", output: "xyxy", isSample: false },
            { input: "aaa\naa\nb", output: "ba", isSample: false },
            { input: "hello world\no\n0", output: "hell0 w0rld", isSample: false },
            { input: "abcdef\nxyz\nabc", output: "abcdef", isSample: false },
            { input: "aaaa\na\nbb", output: "bbbbbbbb", isSample: false },
            { input: "mississippi\nss\nS", output: "miSiSippi", isSample: false },
        ],
    },
    {
        title: "Alternate Sorting",
        slug: "alternate-sorting",
        difficulty: Difficulty.EASY,
        statement: `Rearrange array in order: max, min, 2nd max, 2nd min, etc.`,
        inputFormat: `Integer n\nn integers`,
        outputFormat: `Rearranged array.`,
        constraints: `1 <= n <= 10^4`,
        sampleInput: `6\n1 2 3 4 5 6`,
        sampleOutput: `6 1 5 2 4 3`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "sorting"],
        testCases: [
            { input: "6\n1 2 3 4 5 6", output: "6 1 5 2 4 3", isSample: true },
            { input: "1\n5", output: "5", isSample: false },
            { input: "2\n1 2", output: "2 1", isSample: false },
            { input: "3\n10 20 30", output: "30 10 20", isSample: false },
            { input: "5\n5 4 3 2 1", output: "5 1 4 2 3", isSample: false },
            { input: "4\n1 1 1 1", output: "1 1 1 1", isSample: false },
            { input: "7\n7 6 5 4 3 2 1", output: "7 1 6 2 5 3 4", isSample: false },
            { input: "4\n100 200 300 400", output: "400 100 300 200", isSample: false },
            { input: "5\n1 2 3 4 5", output: "5 1 4 2 3", isSample: false },
            { input: "8\n8 7 6 5 4 3 2 1", output: "8 1 7 2 6 3 5 4", isSample: false },
            { input: "3\n1 1 1", output: "1 1 1", isSample: false },
        ],
    },
    {
        title: "Pascal Triangle",
        slug: "pascal-triangle",
        difficulty: Difficulty.EASY,
        statement: `Print first n rows of Pascal's triangle.`,
        inputFormat: `Integer n.`,
        outputFormat: `n rows, ith row has i integers.`,
        constraints: `1 <= n <= 20`,
        sampleInput: `5`,
        sampleOutput: `1\n1 1\n1 2 1\n1 3 3 1\n1 4 6 4 1`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math", "implementation"],
        testCases: [
            { input: "5", output: "1\n1 1\n1 2 1\n1 3 3 1\n1 4 6 4 1", isSample: true },
            { input: "1", output: "1", isSample: false },
            { input: "2", output: "1\n1 1", isSample: false },
            { input: "3", output: "1\n1 1\n1 2 1", isSample: false },
            { input: "4", output: "1\n1 1\n1 2 1\n1 3 3 1", isSample: false },
            { input: "6", output: "1\n1 1\n1 2 1\n1 3 3 1\n1 4 6 4 1\n1 5 10 10 5 1", isSample: false },
            { input: "7", output: "1\n1 1\n1 2 1\n1 3 3 1\n1 4 6 4 1\n1 5 10 10 5 1\n1 6 15 20 15 6 1", isSample: false },
        ],
    },
    {
        title: "Pyramid Pattern Stars",
        slug: "pyramid-pattern-stars",
        difficulty: Difficulty.EASY,
        statement: `Print a centered pyramid of height n using *. Row i (0-based) has 2*i+1 stars.`,
        inputFormat: `Integer n.`,
        outputFormat: `n lines (centered).`,
        constraints: `1 <= n <= 20`,
        sampleInput: `3`,
        sampleOutput: `  *\n ***\n*****`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["implementation"],
        testCases: [
            { input: "3", output: "  *\n ***\n*****", isSample: true },
            { input: "1", output: "*", isSample: false },
            { input: "2", output: " *\n***", isSample: false },
            { input: "4", output: "   *\n  ***\n *****\n*******", isSample: false },
            { input: "5", output: "    *\n   ***\n  *****\n *******\n*********", isSample: false },
        ],
    },
    {
        title: "Prime Numbers in Range",
        slug: "prime-numbers-in-range",
        difficulty: Difficulty.EASY,
        statement: `Print all primes in range [L, R] (inclusive), comma and space separated. If none, print blank.`,
        inputFormat: `Integers L and R.`,
        outputFormat: `Comma-separated primes.`,
        constraints: `1 <= L <= R <= 10^4`,
        sampleInput: `10 20`,
        sampleOutput: `11, 13, 17, 19`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math"],
        testCases: [
            { input: "10 20", output: "11, 13, 17, 19", isSample: true },
            { input: "1 10", output: "2, 3, 5, 7", isSample: false },
            { input: "2 2", output: "2", isSample: false },
            { input: "4 6", output: "5", isSample: false },
            { input: "20 30", output: "23, 29", isSample: false },
            { input: "1 1", output: "", isSample: false },
            { input: "14 16", output: "", isSample: false },
            { input: "1 100", output: "2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97", isSample: false },
            { input: "50 60", output: "53, 59", isSample: false },
            { input: "90 100", output: "97", isSample: false },
            { input: "7 7", output: "7", isSample: false },
        ],
    },
];
