// Part B Questions (Q28-Q55) - Automata/PYQ Pool continued
import { Difficulty, DifficultyType, AMCATQuestion } from "./amcat-questions";

export const partB2Questions: AMCATQuestion[] = [
    {
        title: "LCM of Two Numbers",
        slug: "lcm-of-two-numbers",
        difficulty: Difficulty.EASY,
        statement: `Compute the least common multiple of two integers a and b.`,
        inputFormat: `Two integers a and b.`,
        outputFormat: `Single integer (LCM).`,
        constraints: `1 <= a, b <= 10^4`,
        sampleInput: `12 18`,
        sampleOutput: `36`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math"],
        testCases: [
            { input: "12 18", output: "36", isSample: true },
            { input: "1 1", output: "1", isSample: false },
            { input: "2 3", output: "6", isSample: false },
            { input: "4 6", output: "12", isSample: false },
            { input: "5 5", output: "5", isSample: false },
            { input: "7 11", output: "77", isSample: false },
            { input: "100 25", output: "100", isSample: false },
            { input: "15 20", output: "60", isSample: false },
            { input: "8 12", output: "24", isSample: false },
            { input: "9 6", output: "18", isSample: false },
            { input: "17 19", output: "323", isSample: false },
        ],
    },
    {
        title: "Fibonacci Series",
        slug: "fibonacci-series",
        difficulty: Difficulty.EASY,
        statement: `Print first n Fibonacci numbers starting from 0, 1, ...`,
        inputFormat: `Integer n.`,
        outputFormat: `n integers (space-separated).`,
        constraints: `1 <= n <= 20`,
        sampleInput: `7`,
        sampleOutput: `0 1 1 2 3 5 8`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math", "implementation"],
        testCases: [
            { input: "7", output: "0 1 1 2 3 5 8", isSample: true },
            { input: "1", output: "0", isSample: false },
            { input: "2", output: "0 1", isSample: false },
            { input: "3", output: "0 1 1", isSample: false },
            { input: "5", output: "0 1 1 2 3", isSample: false },
            { input: "10", output: "0 1 1 2 3 5 8 13 21 34", isSample: false },
            { input: "8", output: "0 1 1 2 3 5 8 13", isSample: false },
            { input: "12", output: "0 1 1 2 3 5 8 13 21 34 55 89", isSample: false },
            { input: "4", output: "0 1 1 2", isSample: false },
            { input: "15", output: "0 1 1 2 3 5 8 13 21 34 55 89 144 233 377", isSample: false },
        ],
    },
    {
        title: "Armstrong Number Check",
        slug: "armstrong-number-check",
        difficulty: Difficulty.EASY,
        statement: `Check if integer n is an Armstrong number. An Armstrong number equals sum of its digits each raised to the power of digit count.`,
        inputFormat: `Integer n.`,
        outputFormat: `YES or NO.`,
        constraints: `0 <= n <= 10^6`,
        sampleInput: `153`,
        sampleOutput: `YES`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math"],
        testCases: [
            { input: "153", output: "YES", isSample: true },
            { input: "123", output: "NO", isSample: false },
            { input: "0", output: "YES", isSample: false },
            { input: "1", output: "YES", isSample: false },
            { input: "370", output: "YES", isSample: false },
            { input: "371", output: "YES", isSample: false },
            { input: "407", output: "YES", isSample: false },
            { input: "100", output: "NO", isSample: false },
            { input: "9", output: "YES", isSample: false },
            { input: "10", output: "NO", isSample: false },
            { input: "1634", output: "YES", isSample: false },
        ],
    },
    {
        title: "Decimal to Binary",
        slug: "decimal-to-binary",
        difficulty: Difficulty.EASY,
        statement: `Convert non-negative integer n to binary string (no leading zeros except for n=0).`,
        inputFormat: `Integer n.`,
        outputFormat: `Binary string.`,
        constraints: `0 <= n <= 10^6`,
        sampleInput: `10`,
        sampleOutput: `1010`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math", "implementation"],
        testCases: [
            { input: "10", output: "1010", isSample: true },
            { input: "0", output: "0", isSample: false },
            { input: "1", output: "1", isSample: false },
            { input: "2", output: "10", isSample: false },
            { input: "7", output: "111", isSample: false },
            { input: "8", output: "1000", isSample: false },
            { input: "15", output: "1111", isSample: false },
            { input: "16", output: "10000", isSample: false },
            { input: "100", output: "1100100", isSample: false },
            { input: "255", output: "11111111", isSample: false },
            { input: "1024", output: "10000000000", isSample: false },
        ],
    },
    {
        title: "Binary to Decimal",
        slug: "binary-to-decimal",
        difficulty: Difficulty.EASY,
        statement: `Convert binary string b to decimal integer.`,
        inputFormat: `Binary string.`,
        outputFormat: `Decimal integer.`,
        constraints: `String length up to 32`,
        sampleInput: `1010`,
        sampleOutput: `10`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math", "implementation"],
        testCases: [
            { input: "1010", output: "10", isSample: true },
            { input: "0", output: "0", isSample: false },
            { input: "1", output: "1", isSample: false },
            { input: "10", output: "2", isSample: false },
            { input: "111", output: "7", isSample: false },
            { input: "1000", output: "8", isSample: false },
            { input: "1111", output: "15", isSample: false },
            { input: "10000", output: "16", isSample: false },
            { input: "1100100", output: "100", isSample: false },
            { input: "11111111", output: "255", isSample: false },
            { input: "10000000000", output: "1024", isSample: false },
        ],
    },
    {
        title: "Maximum Subarray Sum",
        slug: "maximum-subarray-sum",
        difficulty: Difficulty.MEDIUM,
        statement: `Find the maximum sum of any contiguous subarray. At least one element must be included in the subarray.`,
        inputFormat: `Integer n\nn integers (may include negatives)`,
        outputFormat: `Maximum sum.`,
        constraints: `1 <= n <= 10^4`,
        sampleInput: `9\n-2 1 -3 4 -1 2 1 -5 4`,
        sampleOutput: `6`,
        timeLimit: 1000,
        memoryLimit: 256,
        hint: "Kadane's algorithm: track max ending at each position.",
        tags: ["arrays", "dynamic-programming"],
        testCases: [
            { input: "9\n-2 1 -3 4 -1 2 1 -5 4", output: "6", isSample: true },
            { input: "1\n5", output: "5", isSample: false },
            { input: "1\n-5", output: "-5", isSample: false },
            { input: "5\n1 2 3 4 5", output: "15", isSample: false },
            { input: "5\n-1 -2 -3 -4 -5", output: "-1", isSample: false },
            { input: "6\n5 -1 5 -1 5 -1", output: "12", isSample: false },
            { input: "3\n-1 2 -1", output: "2", isSample: false },
            { input: "4\n1 -1 1 -1", output: "1", isSample: false },
            { input: "5\n0 0 0 0 0", output: "0", isSample: false },
            { input: "7\n-2 -3 4 -1 -2 1 5", output: "7", isSample: false },
            { input: "3\n3 -2 5", output: "6", isSample: false },
        ],
    },
    {
        title: "Spiral Print of Matrix",
        slug: "spiral-print-matrix",
        difficulty: Difficulty.MEDIUM,
        statement: `Print matrix elements in spiral order (clockwise from top-left): right → down → left → up, then inward.`,
        inputFormat: `Integers r and c\nr rows of c integers each`,
        outputFormat: `Elements in spiral order (space-separated).`,
        constraints: `1 <= r, c <= 50`,
        sampleInput: `3 3\n1 2 3\n4 5 6\n7 8 9`,
        sampleOutput: `1 2 3 6 9 8 7 4 5`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "implementation"],
        testCases: [
            { input: "3 3\n1 2 3\n4 5 6\n7 8 9", output: "1 2 3 6 9 8 7 4 5", isSample: true },
            { input: "1 1\n5", output: "5", isSample: false },
            { input: "1 3\n1 2 3", output: "1 2 3", isSample: false },
            { input: "3 1\n1\n2\n3", output: "1 2 3", isSample: false },
            { input: "2 2\n1 2\n3 4", output: "1 2 4 3", isSample: false },
            { input: "2 3\n1 2 3\n4 5 6", output: "1 2 3 6 5 4", isSample: false },
            { input: "3 2\n1 2\n3 4\n5 6", output: "1 2 4 6 5 3", isSample: false },
            { input: "4 4\n1 2 3 4\n5 6 7 8\n9 10 11 12\n13 14 15 16", output: "1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10", isSample: false },
        ],
    },
    {
        title: "Bubble Sort",
        slug: "bubble-sort",
        difficulty: Difficulty.EASY,
        statement: `Sort an array using bubble sort.`,
        inputFormat: `Integer n\nn integers`,
        outputFormat: `Sorted array.`,
        constraints: `1 <= n <= 10^3`,
        sampleInput: `5\n5 1 4 2 8`,
        sampleOutput: `1 2 4 5 8`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["sorting"],
        testCases: [
            { input: "5\n5 1 4 2 8", output: "1 2 4 5 8", isSample: true },
            { input: "1\n5", output: "5", isSample: false },
            { input: "2\n2 1", output: "1 2", isSample: false },
            { input: "6\n6 5 4 3 2 1", output: "1 2 3 4 5 6", isSample: false },
            { input: "4\n1 1 1 1", output: "1 1 1 1", isSample: false },
            { input: "5\n1 2 3 4 5", output: "1 2 3 4 5", isSample: false },
            { input: "7\n7 3 5 1 9 2 8", output: "1 2 3 5 7 8 9", isSample: false },
            { input: "3\n100 50 75", output: "50 75 100", isSample: false },
            { input: "4\n10 30 20 40", output: "10 20 30 40", isSample: false },
            { input: "5\n5 5 5 5 5", output: "5 5 5 5 5", isSample: false },
        ],
    },
    {
        title: "Count Triangle Triplets",
        slug: "count-triangle-triplets",
        difficulty: Difficulty.MEDIUM,
        statement: `Given array arr, count triplets (i, j, k) with 0 <= i < j < k < n where the three values form a valid triangle (satisfy triangle inequality).`,
        inputFormat: `Integer n\nn integers`,
        outputFormat: `Count of valid triplets.`,
        constraints: `1 <= n <= 500`,
        sampleInput: `5\n4 6 3 7 2`,
        sampleOutput: `3`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "sorting"],
        testCases: [
            { input: "5\n4 6 3 7 2", output: "3", isSample: true },
            { input: "3\n3 4 5", output: "1", isSample: false },
            { input: "4\n1 1 1 1", output: "4", isSample: false },
            { input: "3\n1 2 10", output: "0", isSample: false },
            { input: "5\n5 5 5 5 5", output: "10", isSample: false },
            { input: "4\n3 4 5 6", output: "4", isSample: false },
            { input: "6\n1 2 3 4 5 6", output: "7", isSample: false },
            { input: "3\n2 2 2", output: "1", isSample: false },
            { input: "4\n10 20 30 40", output: "1", isSample: false },
            { input: "5\n6 7 8 9 10", output: "10", isSample: false },
        ],
    },
    {
        title: "Primes Below N",
        slug: "primes-below-n",
        difficulty: Difficulty.EASY,
        statement: `Print all primes strictly less than N, separated by comma and space.`,
        inputFormat: `Integer N.`,
        outputFormat: `Comma-separated primes.`,
        constraints: `2 <= N <= 1000`,
        sampleInput: `20`,
        sampleOutput: `2, 3, 5, 7, 11, 13, 17, 19`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math"],
        testCases: [
            { input: "20", output: "2, 3, 5, 7, 11, 13, 17, 19", isSample: true },
            { input: "2", output: "", isSample: false },
            { input: "3", output: "2", isSample: false },
            { input: "10", output: "2, 3, 5, 7", isSample: false },
            { input: "50", output: "2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47", isSample: false },
            { input: "5", output: "2, 3", isSample: false },
            { input: "8", output: "2, 3, 5, 7", isSample: false },
            { input: "30", output: "2, 3, 5, 7, 11, 13, 17, 19, 23, 29", isSample: false },
            { input: "15", output: "2, 3, 5, 7, 11, 13", isSample: false },
            { input: "4", output: "2, 3", isSample: false },
        ],
    },
    {
        title: "Sum of Digits",
        slug: "sum-of-digits",
        difficulty: Difficulty.EASY,
        statement: `Compute sum of digits of a non-negative integer.`,
        inputFormat: `Integer n.`,
        outputFormat: `Sum of digits.`,
        constraints: `0 <= n <= 10^9`,
        sampleInput: `1895`,
        sampleOutput: `23`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math"],
        testCases: [
            { input: "1895", output: "23", isSample: true },
            { input: "0", output: "0", isSample: false },
            { input: "1", output: "1", isSample: false },
            { input: "10", output: "1", isSample: false },
            { input: "99", output: "18", isSample: false },
            { input: "100", output: "1", isSample: false },
            { input: "123", output: "6", isSample: false },
            { input: "999", output: "27", isSample: false },
            { input: "12345", output: "15", isSample: false },
            { input: "111111", output: "6", isSample: false },
            { input: "9999999", output: "63", isSample: false },
        ],
    },
    {
        title: "Number Pattern Alternating",
        slug: "number-pattern-alternating",
        difficulty: Difficulty.MEDIUM,
        statement: `Print n rows. Odd rows have numbers in increasing order; even rows in decreasing. Numbers are consecutive across rows.`,
        inputFormat: `Integer n.`,
        outputFormat: `n lines (numbers separated by *).`,
        constraints: `1 <= n <= 10`,
        sampleInput: `4`,
        sampleOutput: `1*2*3*4*17*18*19*20\n5*6*7*14*15*16\n8*9*12*13\n10*11`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["implementation"],
        testCases: [
            { input: "4", output: "1*2*3*4*17*18*19*20\n5*6*7*14*15*16\n8*9*12*13\n10*11", isSample: true },
            { input: "1", output: "1", isSample: false },
            { input: "2", output: "1*2*3*4\n5*6", isSample: false },
            { input: "3", output: "1*2*3*10*11*12\n4*5*8*9\n6*7", isSample: false },
        ],
    },
    {
        title: "Solid Square of Stars",
        slug: "solid-square-stars",
        difficulty: Difficulty.EASY,
        statement: `Print an n x n solid square using *.`,
        inputFormat: `Integer n.`,
        outputFormat: `n lines, each with n stars.`,
        constraints: `1 <= n <= 20`,
        sampleInput: `3`,
        sampleOutput: `***\n***\n***`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["implementation"],
        testCases: [
            { input: "3", output: "***\n***\n***", isSample: true },
            { input: "1", output: "*", isSample: false },
            { input: "2", output: "**\n**", isSample: false },
            { input: "4", output: "****\n****\n****\n****", isSample: false },
            { input: "5", output: "*****\n*****\n*****\n*****\n*****", isSample: false },
        ],
    },
    {
        title: "Maze Path Reachability",
        slug: "maze-path-reachability",
        difficulty: Difficulty.MEDIUM,
        statement: `Given a grid where 0=wall, 1=free path, 9=cheese, and starting position (0,0), determine if mouse can reach any cell with value 9. Return 1 if reachable, else 0.`,
        inputFormat: `Integers r and c\nr rows of c integers each`,
        outputFormat: `1 or 0.`,
        constraints: `1 <= r, c <= 10`,
        sampleInput: `3 3\n1 1 1\n0 1 1\n0 1 0`,
        sampleOutput: `0`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["graphs"],
        testCases: [
            { input: "3 3\n1 1 1\n0 1 1\n0 1 0", output: "0", isSample: true },
            { input: "3 3\n1 1 9\n0 1 1\n0 1 0", output: "1", isSample: false },
            { input: "1 1\n9", output: "1", isSample: false },
            { input: "1 1\n1", output: "0", isSample: false },
            { input: "2 2\n1 9\n0 0", output: "1", isSample: false },
            { input: "3 3\n1 0 0\n1 0 0\n1 1 9", output: "1", isSample: false },
            { input: "2 2\n0 1\n1 9", output: "0", isSample: false },
        ],
    },
    {
        title: "Distinct Elements from Two Arrays",
        slug: "distinct-elements-two-arrays",
        difficulty: Difficulty.EASY,
        statement: `Given two arrays, print all elements that appear in exactly one of them (not common). Also print their sum.`,
        inputFormat: `Integer n1, then n1 integers\nInteger n2, then n2 integers`,
        outputFormat: `Line 1: distinct elements (space-separated)\nLine 2: sum of those elements`,
        constraints: `1 <= n1, n2 <= 10^3`,
        sampleInput: `5\n1 2 3 4 5\n3\n2 6 8 10`,
        sampleOutput: `1 3 4 5 6 8 10\n37`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays"],
        testCases: [
            { input: "5\n1 2 3 4 5\n3\n2 6 8 10", output: "1 3 4 5 6 8 10\n37", isSample: true },
            { input: "2\n1 2\n2\n1 2", output: "\n0", isSample: false },
            { input: "3\n1 2 3\n3\n4 5 6", output: "1 2 3 4 5 6\n21", isSample: false },
            { input: "2\n1 1\n2\n2 2", output: "1 2\n3", isSample: false },
            { input: "4\n5 6 7 8\n2\n7 9", output: "5 6 8 9\n28", isSample: false },
        ],
    },
    {
        title: "Swap Alternate Elements",
        slug: "swap-alternate-elements",
        difficulty: Difficulty.EASY,
        statement: `Swap adjacent pairs in an array: swap (0,1), (2,3), (4,5), etc. If length is odd, last element stays.`,
        inputFormat: `Integer n\nn integers`,
        outputFormat: `Modified array.`,
        constraints: `1 <= n <= 10^3`,
        sampleInput: `5\n10 20 30 40 50`,
        sampleOutput: `20 10 40 30 50`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays"],
        testCases: [
            { input: "5\n10 20 30 40 50", output: "20 10 40 30 50", isSample: true },
            { input: "1\n5", output: "5", isSample: false },
            { input: "2\n1 2", output: "2 1", isSample: false },
            { input: "4\n1 2 3 4", output: "2 1 4 3", isSample: false },
            { input: "3\n10 20 30", output: "20 10 30", isSample: false },
            { input: "6\n1 2 3 4 5 6", output: "2 1 4 3 6 5", isSample: false },
            { input: "4\n5 5 5 5", output: "5 5 5 5", isSample: false },
            { input: "7\n1 2 3 4 5 6 7", output: "2 1 4 3 6 5 7", isSample: false },
        ],
    },
    {
        title: "Print Pascal Pattern Concatenated",
        slug: "pascal-pattern-concatenated",
        difficulty: Difficulty.MEDIUM,
        statement: `Print first n rows of Pascal's triangle as concatenated digits (valid for small n where no number exceeds single digit or two digits).`,
        inputFormat: `Integer n.`,
        outputFormat: `n lines.`,
        constraints: `1 <= n <= 5`,
        sampleInput: `5`,
        sampleOutput: `1\n11\n121\n1331\n14641`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math", "implementation"],
        testCases: [
            { input: "5", output: "1\n11\n121\n1331\n14641", isSample: true },
            { input: "1", output: "1", isSample: false },
            { input: "2", output: "1\n11", isSample: false },
            { input: "3", output: "1\n11\n121", isSample: false },
            { input: "4", output: "1\n11\n121\n1331", isSample: false },
        ],
    },
    {
        title: "Alternating Edge Pattern",
        slug: "alternating-edge-pattern",
        difficulty: Difficulty.MEDIUM,
        statement: `For input n, print n lines. Odd-numbered lines (1, 3, 5, ...) print repeated digit ending with next digit. Even-numbered lines start with next digit then repeat current digit.`,
        inputFormat: `Integer n.`,
        outputFormat: `n lines.`,
        constraints: `1 <= n <= 10`,
        sampleInput: `6`,
        sampleOutput: `1111112\n3222222\n3333334\n5444444\n5555556\n7666666`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["implementation"],
        testCases: [
            { input: "6", output: "1111112\n3222222\n3333334\n5444444\n5555556\n7666666", isSample: true },
            { input: "1", output: "1111112", isSample: false },
            { input: "2", output: "1111112\n3222222", isSample: false },
            { input: "3", output: "1111112\n3222222\n3333334", isSample: false },
            { input: "4", output: "1111112\n3222222\n3333334\n5444444", isSample: false },
        ],
    },
    {
        title: "Two N Minus One Rows Pattern",
        slug: "two-n-minus-one-rows-pattern",
        difficulty: Difficulty.MEDIUM,
        statement: `Print 2*n-1 lines. Top half increases width from 1 to n; bottom half mirrors down to 1. Each row contains same digit repeated (width of row) times.`,
        inputFormat: `Integer n.`,
        outputFormat: `2*n-1 lines.`,
        constraints: `1 <= n <= 10`,
        sampleInput: `4`,
        sampleOutput: `3\n44\n555\n6666\n555\n44\n3`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["implementation"],
        testCases: [
            { input: "4", output: "3\n44\n555\n6666\n555\n44\n3", isSample: true },
            { input: "1", output: "0", isSample: false },
            { input: "2", output: "1\n22\n1", isSample: false },
            { input: "3", output: "2\n33\n444\n33\n2", isSample: false },
        ],
    },
    {
        title: "Mixed Number Star Pattern",
        slug: "mixed-number-star-pattern",
        difficulty: Difficulty.HARD,
        statement: `Print n rows. Each row starts with some hyphens (increasing), then prints a number sequence separated by *. Outer numbers increase globally; right-side block is ordered oppositely.`,
        inputFormat: `Integer n.`,
        outputFormat: `n lines.`,
        constraints: `1 <= n <= 5`,
        sampleInput: `4`,
        sampleOutput: `1*2*3*4*17*18*19*20\n--5*6*7*14*15*16\n----8*9*12*13\n------10*11`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["implementation"],
        testCases: [
            { input: "4", output: "1*2*3*4*17*18*19*20\n--5*6*7*14*15*16\n----8*9*12*13\n------10*11", isSample: true },
            { input: "1", output: "1", isSample: false },
            { input: "2", output: "1*2*5*6\n--3*4", isSample: false },
            { input: "3", output: "1*2*3*10*11*12\n--4*5*8*9\n----6*7", isSample: false },
        ],
    },
    {
        title: "Count Occurrences of Digit",
        slug: "count-occurrences-digit",
        difficulty: Difficulty.EASY,
        statement: `Given integer num1 and single digit num2 (0≤d≤9), count how many times num2 appears in the decimal representation of num1.`,
        inputFormat: `Two integers num1 and num2.`,
        outputFormat: `Count.`,
        constraints: `0 <= num1 <= 10^9\n0 <= num2 <= 9`,
        sampleInput: `1222212 2`,
        sampleOutput: `5`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math", "strings"],
        testCases: [
            { input: "1222212 2", output: "5", isSample: true },
            { input: "0 0", output: "1", isSample: false },
            { input: "111 1", output: "3", isSample: false },
            { input: "123456 7", output: "0", isSample: false },
            { input: "999999 9", output: "6", isSample: false },
            { input: "10 0", output: "1", isSample: false },
            { input: "100 0", output: "2", isSample: false },
            { input: "555 5", output: "3", isSample: false },
            { input: "12345 3", output: "1", isSample: false },
            { input: "11111 1", output: "5", isSample: false },
        ],
    },
    {
        title: "Three Dice Sum Outcomes",
        slug: "three-dice-sum-outcomes",
        difficulty: Difficulty.EASY,
        statement: `Given target sum S, count ordered triples (a, b, c) where each is 1≤d≤6 (standard die) and a + b + c = S.`,
        inputFormat: `Integer S.`,
        outputFormat: `Count.`,
        constraints: `3 <= S <= 18`,
        sampleInput: `5`,
        sampleOutput: `6`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math", "implementation"],
        testCases: [
            { input: "5", output: "6", isSample: true },
            { input: "3", output: "1", isSample: false },
            { input: "4", output: "3", isSample: false },
            { input: "6", output: "10", isSample: false },
            { input: "10", output: "27", isSample: false },
            { input: "11", output: "27", isSample: false },
            { input: "18", output: "1", isSample: false },
            { input: "7", output: "15", isSample: false },
            { input: "9", output: "25", isSample: false },
            { input: "12", output: "25", isSample: false },
        ],
    },
    {
        title: "Armstrong Numbers in Range",
        slug: "armstrong-numbers-in-range",
        difficulty: Difficulty.EASY,
        statement: `Print all Armstrong numbers in range [L, R] (inclusive) in ascending order.`,
        inputFormat: `Two integers L and R.`,
        outputFormat: `Armstrong numbers (space-separated).`,
        constraints: `1 <= L <= R <= 10000`,
        sampleInput: `100 400`,
        sampleOutput: `153 370 371`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math"],
        testCases: [
            { input: "100 400", output: "153 370 371", isSample: true },
            { input: "1 10", output: "1 2 3 4 5 6 7 8 9", isSample: false },
            { input: "100 200", output: "153", isSample: false },
            { input: "370 371", output: "370 371", isSample: false },
            { input: "400 500", output: "407", isSample: false },
            { input: "1 1", output: "1", isSample: false },
            { input: "150 155", output: "153", isSample: false },
            { input: "500 1000", output: "", isSample: false },
        ],
    },
    {
        title: "Character Frequency",
        slug: "character-frequency",
        difficulty: Difficulty.EASY,
        statement: `Given a lowercase string, count character frequencies and print character count (one per line) in alphabetical order; include only non-zero counts.`,
        inputFormat: `Single lowercase string.`,
        outputFormat: `Lines of character count.`,
        constraints: `String length up to 10^3`,
        sampleInput: `helloworld`,
        sampleOutput: `d 1\ne 1\nh 1\nl 3\no 2\nr 1\nw 1`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["strings", "implementation"],
        testCases: [
            { input: "helloworld", output: "d 1\ne 1\nh 1\nl 3\no 2\nr 1\nw 1", isSample: true },
            { input: "a", output: "a 1", isSample: false },
            { input: "aaa", output: "a 3", isSample: false },
            { input: "abc", output: "a 1\nb 1\nc 1", isSample: false },
            { input: "zzz", output: "z 3", isSample: false },
            { input: "abcabc", output: "a 2\nb 2\nc 2", isSample: false },
            { input: "programming", output: "a 1\ng 2\ni 1\nm 2\nn 1\no 1\np 1\nr 2", isSample: false },
        ],
    },
    {
        title: "Palindrome Number Check",
        slug: "palindrome-number-check",
        difficulty: Difficulty.EASY,
        statement: `Determine if integer n is a palindrome without converting to string. Print YES or NO.`,
        inputFormat: `Integer n.`,
        outputFormat: `YES or NO.`,
        constraints: `0 <= n <= 10^9`,
        sampleInput: `12321`,
        sampleOutput: `YES`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["math"],
        testCases: [
            { input: "12321", output: "YES", isSample: true },
            { input: "123", output: "NO", isSample: false },
            { input: "0", output: "YES", isSample: false },
            { input: "1", output: "YES", isSample: false },
            { input: "11", output: "YES", isSample: false },
            { input: "10", output: "NO", isSample: false },
            { input: "121", output: "YES", isSample: false },
            { input: "1001", output: "YES", isSample: false },
            { input: "1234321", output: "YES", isSample: false },
            { input: "12345", output: "NO", isSample: false },
            { input: "99", output: "YES", isSample: false },
        ],
    },
    {
        title: "Reverse Each Word in Sentence",
        slug: "reverse-each-word-in-sentence",
        difficulty: Difficulty.EASY,
        statement: `Reverse each word in a sentence individually; keep word order same. Maintain single space between words.`,
        inputFormat: `One line (sentence with words separated by spaces).`,
        outputFormat: `Transformed sentence.`,
        constraints: `Line length up to 10^3`,
        sampleInput: `amcat automata test`,
        sampleOutput: `tacma atamoua tset`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["strings"],
        testCases: [
            { input: "amcat automata test", output: "tacma atamoua tset", isSample: true },
            { input: "hello", output: "olleh", isSample: false },
            { input: "a b c", output: "a b c", isSample: false },
            { input: "ab cd", output: "ba dc", isSample: false },
            { input: "Hello World", output: "olleH dlroW", isSample: false },
            { input: "programming is fun", output: "gnimmargorp si nuf", isSample: false },
            { input: "one", output: "eno", isSample: false },
            { input: "abc def ghi", output: "cba fed ihg", isSample: false },
        ],
    },
    {
        title: "Pythagorean Triplet Exists",
        slug: "pythagorean-triplet-exists",
        difficulty: Difficulty.MEDIUM,
        statement: `Given array arr, return True if there exist indices i < j < k with arr[i]^2 + arr[j]^2 = arr[k]^2 (in any assignment, i.e., some element serves as hypotenuse). Otherwise return False.`,
        inputFormat: `Integer n\nn integers`,
        outputFormat: `True or False.`,
        constraints: `1 <= n <= 100`,
        sampleInput: `5\n3 1 4 6 5`,
        sampleOutput: `True`,
        timeLimit: 1000,
        memoryLimit: 256,
        tags: ["arrays", "math"],
        testCases: [
            { input: "5\n3 1 4 6 5", output: "True", isSample: true },
            { input: "4\n5 12 13 10", output: "True", isSample: false },
            { input: "3\n1 2 3", output: "False", isSample: false },
            { input: "3\n3 4 5", output: "True", isSample: false },
            { input: "4\n6 8 10 15", output: "True", isSample: false },
            { input: "5\n1 1 1 1 1", output: "False", isSample: false },
            { input: "4\n5 5 5 5", output: "False", isSample: false },
            { input: "5\n8 15 17 20 25", output: "True", isSample: false },
            { input: "3\n7 24 25", output: "True", isSample: false },
            { input: "4\n1 2 4 8", output: "False", isSample: false },
        ],
    },
];
